import os
import numpy as np
from acados_template import AcadosModel
from casadi import (
    MX,
    vertcat,
    horzcat,
    sin,
    cos,
    atan2,
    sqrt,
    exp,
    jacobian,
    interpolant,
    bspline,
    Function,
    DM,
    CodeGenerator,
)


class DebugRegistry:
    def __init__(self):
        self.exprs = {}

    def add(self, name, expr):
        self.exprs[name] = expr

    def build_functions(self, inputs):
        funcs = {}
        for name, expr in self.exprs.items():
            funcs[name] = Function(name, inputs, [expr])
        return funcs

    def generate_c(self, filename, inputs):
        opts = {"cpp": True, "with_header": True}
        C = CodeGenerator(filename, opts)
        for name, expr in self.exprs.items():
            f = Function(name, inputs, [expr])
            C.add(f)
        C.generate()

# Full disclosure written by claude with some modifications
class ParamVector:
    """Maintains an ordered list of (name, CasADi symbol) pairs and tracks
    the flat index of each entry in the acados parameter vector.
 
    Scalar symbols contribute 1 slot; vector symbols contribute shape[0] slots.
 
    Usage:
        pv = ParamVector()
        pv.add("x_coeff", x_coeff_sym)   # vector symbol
        pv.add("Q_c", Q_c_sym)            # scalar symbol
        p = pv.as_casadi_vector()         # vertcat of all syms, for acados
        pv.write_cpp_header(path)         # emit the generated header
    """
 
    def __init__(self):
        self._entries: list[tuple[str, object]] = []  # (name, casadi_sym)
 
    def add(self, name: str, sym) -> "ParamVector":
        self._entries.append((name, sym))
        return self  # allow chaining
 
    def as_casadi_vector(self):
        return vertcat(*[sym for _, sym in self._entries])
 
    def _index_map(self) -> dict[str, tuple[int, int]]:
        """Returns {name: (start_index, size)}."""
        result = {}
        idx = 0
        for name, sym in self._entries:
            size = sym.shape[0]
            result[name] = (idx, size)
            idx += size
        return result
 
    def write_cpp_header(self, path: str, namespace: str = "mpcc::param_indices") -> None:
        """Writes a self-contained C++ header with constexpr index constants.
 
        Scalar params get a single `k_<name>` constant.
        Vector params additionally get a `k_<name>_sz` constant.
 
        The header is guarded and stamped with a warning so it is never
        edited by hand.
        """
        guard = namespace.replace("::", "_").upper() + "_H"
        index_map = self._index_map()
 
        lines = [
            f"#ifndef CASADI_UNICYCLE_MODEL_MPCC_PARAM_INCIDES",
            f"#define CASADI_UNICYCLE_MODEL_MPCC_PARAM_INCIDES",
            f"// clang-format off",
            f"// AUTO-GENERATED by model.py — DO NOT EDIT MANUALLY.",
            f"// Re-run the model generation script to update this file.",
            f"#include <cstddef>",
            f"",
            f"namespace {namespace} {{",
            f"",
            f"// Total number of parameters in the acados parameter vector.",
            f"static constexpr std::size_t kNP = {sum(s for _, s in index_map.values())};",
            f"static constexpr std::size_t kNP_Scalar = {len([s for s, sz in index_map.values() if sz == 1])};",
            f"",
        ]
 
        for name, (start, size) in index_map.items():
            lines.append(f"// '{name}': {size} element(s) starting at index {start}")
            lines.append(f"static constexpr std::size_t k_{name} = {start};")
            if size > 1:
                lines.append(f"static constexpr std::size_t k_{name}_sz = {size};")
            lines.append("")
 
        lines += [
            f"}}  // namespace {namespace}",
            f"// clang-format on",
            f"#endif",
        ]
 
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")


def export_mpcc_ode_model_spline_tube_cbf(params, output_dir) -> AcadosModel:

    model_name = "unicycle_model_mpcc"

    # set up states & controls
    x1 = MX.sym("x1")
    y1 = MX.sym("y1")
    theta1 = MX.sym("theta1")
    v1 = MX.sym("v1")
    s1 = MX.sym("s1")
    sdot1 = MX.sym("sdot1")

    x = vertcat(x1, y1, theta1, v1, s1, sdot1)

    a = MX.sym("a")
    w = MX.sym("w")
    sddot = MX.sym("sddot")

    u = vertcat(a, w, sddot)

    x_coeff = MX.sym("x_coeffs", params["mpc_ref_samples"])
    y_coeff = MX.sym("y_coeffs", params["mpc_ref_samples"])

    d_abv_coeff = MX.sym("d_above_coeffs", params["tube_poly_degree"] + 1)
    d_blw_coeff = MX.sym("d_below_coeffs", params["tube_poly_degree"] + 1)

    L_path = MX.sym("L_path", 1)

    # arc_len_knots = np.linspace(0, params["ref_length_size"], params["mpc_ref_samples"])
    arc_len_knots = np.linspace(0, 1, params["mpc_ref_samples"])

    xspl = MX.sym("xspl", 1, 1)
    yspl = MX.sym("yspl", 1, 1)

    interp_x = interpolant("interp_x", "bspline", [arc_len_knots.tolist()])
    interp_exp_x = interp_x(xspl, x_coeff)
    xr_func = Function("xr", [xspl, x_coeff], [interp_exp_x])

    interp_y = interpolant("interp_y", "bspline", [arc_len_knots.tolist()])
    interp_exp_y = interp_y(yspl, y_coeff)
    yr_func = Function("yr", [yspl, y_coeff], [interp_exp_y])

    s_norm = s1 / L_path
    xr = xr_func(s_norm, x_coeff)
    yr = yr_func(s_norm, y_coeff)

    # dont need to multiply by L_path.
    xr_dot = jacobian(xr, s1)
    yr_dot = jacobian(yr, s1)

    d_abv = 0
    d_blw = 0
    for i in range(params["tube_poly_degree"] + 1):
        # d_abv = d_abv + (d_abv_coeff[i] * s1**i)
        # d_blw = d_blw + (d_blw_coeff[i] * s1**i)
        d_abv = d_abv + (d_abv_coeff[i] * s_norm**i)
        d_blw = d_blw + (d_blw_coeff[i] * s_norm**i)

    # phi_r = atan2(xr_dot, yr_dot)
    phi_r = atan2(yr_dot, xr_dot)

    e_c = sin(phi_r) * (x1 - xr) - cos(phi_r) * (y1 - yr)
    e_l = -cos(phi_r) * (x1 - xr) - sin(phi_r) * (y1 - yr)

    # xdot
    x1_dot = MX.sym("x1_dot")
    y1_dot = MX.sym("y1_dot")
    theta1_dot = MX.sym("theta1_dot")
    v1_dot = MX.sym("v1_dot")
    s1_dot = MX.sym("s1_dot")
    sdot1_dot = MX.sym("sdot1_dot")

    xdot = vertcat(x1_dot, y1_dot, theta1_dot, v1_dot, s1_dot, sdot1_dot)

    # dynamics
    cos_theta = cos(theta1)
    sin_theta = sin(theta1)
    f_expl = vertcat(
        v1 * cos_theta,
        v1 * sin_theta,
        w,
        a,
        sdot1,
        sddot,
    )

    f_impl = xdot - f_expl

    # cost
    Q_c = MX.sym("Q_c")  # 0.1
    Q_l = MX.sym("Q_l")  # 100
    Q_s = MX.sym("Q_s")  # 0.5
    Q_a = 1
    Q_w = 1
    Q_sdd = 1

    cost_expr = (
        Q_c * e_c**2
        + Q_l * e_l**2
        + Q_a * a**2
        + Q_w * w**2
        + Q_sdd * sddot**2
        - Q_s * sdot1
    )

    cost_expr_e = Q_c * e_c**2 + Q_l * e_l**2 - Q_s * sdot1
    # cost_expr = y_expr.T @ Q_mat @ y_expr - Q_s * sdot1
    # cost_expr_e = y_expr_e.T @ Q_mat_e @ y_expr_e - Q_s * sdot1

    # Control Barrier Function
    alpha_abv = MX.sym("alpha_abv")
    alpha_blw = MX.sym("alpha_blw")

    # vector pointing towards the obstacle from the robot
    # roughly equal to norm of trajectory derivative since
    # lag error is nearly 0
    obs_dirx = -sin(phi_r)
    obs_diry = cos(phi_r)
    # obs_dirx = -yr_dot / sqrt(xr_dot**2 + yr_dot**2)
    # obs_diry = xr_dot / sqrt(xr_dot**2 + yr_dot**2)

    signed_d = (x1 - xr) * obs_dirx + (y1 - yr) * obs_diry

    # h_abv = d_abv - signed_d
    # h_blw = signed_d - d_blw

    p_abv = obs_dirx * cos_theta + obs_diry * sin_theta + v1 * 0.05
    h_abv = (d_abv - signed_d) * exp(-p_abv)

    p_blw = -obs_dirx * cos_theta - obs_diry * sin_theta + v1 * 0.05
    h_blw = (signed_d - d_blw) * exp(-p_blw)

    f = vertcat(v1 * cos_theta, v1 * sin_theta, 0, 0, sdot1, 0)
    g = vertcat(
        horzcat(0, 0, 0),
        horzcat(0, 0, 0),
        horzcat(0, 1, 0),
        horzcat(1, 0, 0),
        horzcat(0, 0, 0),
        horzcat(0, 0, 1),
    )

    # HOCBF (second order)
    # dot_h_abv = jacobian(h_abv, x) @ f
    # dot_h_blw = jacobian(h_blw, x) @ f

    # ddot_h_abv = jacobian(dot_h_abv, x) @ f + jacobian(dot_h_abv, x) @ g @ u
    # ddot_h_blw = jacobian(dot_h_blw, x) @ f + jacobian(dot_h_blw, x) @ g @ u

    # ddot{h} >= -\Kappa * \eta, where \eta = {h, \dot{h}}

    # g_u = vertcat(0, 0, w, a, 0, sddot)
    h_dot_abv = jacobian(h_abv, x)
    Lfh_abv = h_dot_abv @ f

    h_dot_blw = jacobian(h_blw, x)
    Lfh_blw = h_dot_blw @ f

    # con_abv = signed_d - d_abv
    # con_blw = d_blw - signed_d
    con_abv = Lfh_abv + h_dot_abv @ g @ u + alpha_abv * h_abv
    con_blw = Lfh_blw + h_dot_blw @ g @ u + alpha_blw * h_blw

    # con_abv = ddot_h_abv + 0.5 * dot_h_abv + alpha * h_abv
    # con_blw = ddot_h_blw + 0.5 * dot_h_blw + alpha * h_blw

    # Control Lyapunov Function
    Ql_c = MX.sym("Ql_c")
    Ql_l = MX.sym("Ql_l")
    gamma = MX.sym("gamma")

    v = Ql_c * e_c**2 + Ql_l * e_l**2  # + Q_s * (sdot1 - v1) ** 2
    lfv = jacobian(v, x) @ f
    lgv = jacobian(v, x) @ g
    lgvu = jacobian(v, x) @ g @ u
    # v_dot = jacobian(v, x) @ f + jacobian(v, x) @ g @ u
    v_dot = lfv + lgvu

    lyap_con = v_dot + gamma * v

    pv = ParamVector()
    pv.add(str(x_coeff), x_coeff)
    pv.add(str(y_coeff), y_coeff)
    pv.add(str(d_abv_coeff), d_abv_coeff)
    pv.add(str(d_blw_coeff), d_blw_coeff)
    pv.add(str(Q_c), Q_c)
    pv.add(str(Q_l), Q_l)
    pv.add(str(Q_s), Q_s)
    pv.add(str(alpha_abv), alpha_abv)
    pv.add(str(alpha_blw), alpha_blw)
    pv.add(str(Ql_c), Ql_c)
    pv.add(str(Ql_l), Ql_l)
    pv.add(str(gamma), gamma)
    pv.add(str(L_path), L_path)
 
    p = pv.as_casadi_vector()
    
    # p = vertcat(
    #     x_coeff,
    #     y_coeff,
    #     d_abv_coeff,
    #     d_blw_coeff,
    #     Q_c,
    #     Q_l,
    #     Q_s,
    #     alpha_abv,
    #     alpha_blw,
    #     Ql_c,
    #     Ql_l,
    #     gamma,
    #     L_path,
    # )

    model = AcadosModel()
    model.f_impl_expr = f_impl
    model.f_expl_expr = f_expl
    model.x = x
    model.u = u
    model.p = p
    model.cost_expr_ext_cost = cost_expr
    model.cost_expr_ext_cost_e = cost_expr_e
    model.xdot = xdot
    model.name = model_name

    # no setting cbf for con_h_expr_e since no u in final step
    # model.con_h_expr_0 = vertcat(con_abv, con_blw)
    # model.con_h_expr = vertcat(con_abv, con_blw)

    model.con_h_expr_0 = vertcat(con_abv, con_blw, lyap_con)
    model.con_h_expr = vertcat(con_abv, con_blw, lyap_con)

    # model.con_h_expr_0 = vertcat(lyap_con)
    # model.con_h_expr = vertcat(lyap_con)

    # store meta information
    model.x_labels = [
        "$x$ [m]",
        "$y$ [m]",
        r"$\theta$ [rad]",
        "$v$ [m]",
        "$s$ []",
        "$sdot$ []",
    ]
    model.u_labels = ["$a$", "$w$", "$sddot$"]
    model.t_label = "$t$ [s]"

    debug = DebugRegistry()

    debug.add("unicycle_model_xr", xr)
    debug.add("unicycle_model_yr", yr)
    debug.add("unicycle_model_xr_dot", xr_dot)
    debug.add("unicycle_model_yr_dot", yr_dot)
    debug.add("unicycle_model_phi_r", phi_r)

    debug.add("unicycle_model_e_c", e_c)
    debug.add("unicycle_model_e_l", e_l)

    debug.add("unicycle_model_signed_d", signed_d)
    debug.add("unicycle_model_p_abv", p_abv)
    debug.add("unicycle_model_p_blw", p_blw)

    debug.add("unicycle_model_d_abv", d_abv)
    debug.add("unicycle_model_d_blw", d_blw)

    debug.add("unicycle_model_h_abv", h_abv)
    debug.add("unicycle_model_h_blw", h_blw)
    debug.add("unicycle_model_Lfh_abv", Lfh_abv)
    debug.add("unicycle_model_Lfh_blw", Lfh_blw)

    debug.add("unicycle_model_Lghu_abv", h_dot_abv @ g @ u)
    debug.add("unicycle_model_Lghu_blw", h_dot_blw @ g @ u)

    debug.add("unicycle_model_Lfv", lfv)
    debug.add("unicycle_model_Lgv", lgv)
    debug.add("unicycle_model_Lgvu", lgvu)
    debug.add("unicycle_model_lyap_const", lyap_con)

    debug_inputs = [
        x,
        u,
        x_coeff,
        y_coeff,
        d_abv_coeff,
        d_blw_coeff,
        Ql_c,
        Ql_l,
        gamma,
        L_path,
    ]

    # folder = "cpp_generated_code"
    if output_dir == "":
        script_dir = os.path.dirname(os.path.abspath(__file__))
        output_dir = os.path.join(script_dir, "cpp_generated_code")

    if not os.path.exists(output_dir):
        os.makedirs(output_dir)

    current_dir = os.getcwd()
    os.chdir(output_dir)

    # Casadi Internals Debug
    fname = "casadi_unicycle_model_mpcc_internals"
    debug.generate_c(fname, debug_inputs)
    os.system(f"gcc -fPIC -shared {fname}.cpp -o lib{fname}.so")

    # Parameter index header
    pv.write_cpp_header(
        "unicycle_model_mpcc_param_indices.h",
        namespace="mpcc::unicycle_params",
    )

    os.chdir(current_dir)

    return model
