from casadi import vertcat

# Full disclosure written by claude with some modifications
class ParamVector:
    """Maintains an ordered list of (name, CasADi symbol) pairs and tracks
    the flat index of each entry in the acados parameter vector.
 
    Scalar symbols contribute 1 slot; vector symbols contribute shape[0] slots.
 
    Usage:
        pv = ParamVector()
        pv.add("x_coeff", x_coeff_sym)   # vector symbol
        pv.add("Q_c", Q_c_sym)            # scalar symbol
        p = pv.as_casadi_vector()         # vertcat of all syms, for acados
        pv.write_cpp_header(path)         # emit the generated header
    """
 
    def __init__(self):
        self._entries: list[tuple[str, object]] = []  # (name, casadi_sym)
 
    def add(self, name: str, sym) -> "ParamVector":
        self._entries.append((name, sym))
        return self  # allow chaining
 
    def as_casadi_vector(self):
        return vertcat(*[sym for _, sym in self._entries])
 
    def _index_map(self) -> dict[str, tuple[int, int]]:
        """Returns {name: (start_index, size)}."""
        result = {}
        idx = 0
        for name, sym in self._entries:
            size = sym.shape[0]
            result[name] = (idx, size)
            idx += size
        return result
 
    def write_cpp_header(self, path: str, namespace: str = "mpcc::param_indices") -> None:
        """Writes a self-contained C++ header with constexpr index constants.
 
        Scalar params get a single `k_<name>` constant.
        Vector params additionally get a `k_<name>_sz` constant.
 
        The header is guarded and stamped with a warning so it is never
        edited by hand.
        """
        guard = namespace.replace("::", "_").upper() + "_INDICES_H"
        index_map = self._index_map()
 
        lines = [
            f"#ifndef {guard}",
            f"#define {guard}",
            f"// clang-format off",
            f"// AUTO-GENERATED by model.py — DO NOT EDIT MANUALLY.",
            f"// Re-run the model generation script to update this file.",
            f"#include <cstddef>",
            f"",
            f"namespace {namespace} {{",
            f"",
            f"// Total number of parameters in the acados parameter vector.",
            f"static constexpr std::size_t kNP = {sum(s for _, s in index_map.values())};",
            f"static constexpr std::size_t kNP_Scalar = {len([s for s, sz in index_map.values() if sz == 1])};",
            f"",
        ]
 
        for name, (start, size) in index_map.items():
            lines.append(f"// '{name}': {size} element(s) starting at index {start}")
            lines.append(f"static constexpr std::size_t k_{name} = {start};")
            if size > 1:
                lines.append(f"static constexpr std::size_t k_{name}_sz = {size};")
            lines.append("")
 
        lines += [
            f"}}  // namespace {namespace}",
            f"// clang-format on",
            f"#endif",
        ]
 
        with open(path, "w") as f:
            f.write("\n".join(lines) + "\n")

